name: automated_testing_framework_plugin_logging
description: Library to use provide logging capabilities and evaluations to the testing framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_logging

version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  automated_testing_framework: ^2.0.0
  flutter:
    sdk: flutter
  form_validation: ^1.0.2+1
  json_class: ^1.0.7+2
  json_theme: ^1.5.0+2
  logging: ">=0.11.4 <2.0.0"
  meta: ^1.2.4
  static_translations: ^1.0.3+1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
