name: 'automated_testing_framework_plugin_logging'
description: 'Library to use provide logging capabilities and evaluations to the testing framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_logging'
version: '4.0.0+6'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.1+6'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+7'
  json_class: '^2.1.2+7'
  json_theme: '^4.0.0+4'
  logging: '^1.0.2'
  static_translations: '^2.1.1+4'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
