name: 'automated_testing_framework_plugin_logging'
description: 'Library to use provide logging capabilities and evaluations to the testing framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_logging'
version: '4.0.0+27'

environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.7+9'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+24'
  json_class: '^2.1.3'
  json_theme: '^4.0.3+2'
  logging: '^1.1.0'
  static_translations: '^2.1.1+19'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
