name: automated_testing_framework_plugin_logging
description: Library to use provide logging capabilities and evaluations to the testing framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_logging

version: 3.0.2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.2.0
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+1
  json_class: ^2.1.2+3
  json_theme: ^3.2.4
  logging: ^1.0.1
  static_translations: ^2.1.0+1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
