name: automated_testing_framework_plugin_logging
description: Library to use provide logging capabilities and evaluations to the testing framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_logging

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  automated_testing_framework: ^1.2.9
  form_validation: ^1.0.1
  json_class: ^1.0.6+1
  json_theme: ^1.3.3+1
  logging: ^0.11.4
  meta: ^1.1.8
  static_translations: ^1.0.3

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
